import React from "react";
import { MyUserButton } from "./MyUserButton";

export const Header = () => {
  return (
    <div className="w-full h-20 bg-blue-950 text-white flex justify-between items-center px-10">
      <div>Header</div>

      <MyUserButton />
    </div>
  );
};

// "use client";

// import type { Metadata } from "next";
// import {
//   ClerkProvider,
//   SignInButton,
//   SignUpButton,
//   SignedIn,
//   SignedOut,
//   UserButton,
// } from "@clerk/nextjs";
// import { Geist, Geist_Mono } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Clerk Next.js Quickstart",
//   description: "Generated by create next app",
// };

// export default function Header() {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body
//           className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//         >
//           <header className="relative w-full h-20 bg-blue-950">
//             <div className="h-full flex items-center justify-end gap-4 px-4">
//               <SignedOut>
//                 <div className="text-white">
//                   <SignInButton />
//                 </div>
//                 <SignUpButton>
//                   <button className="bg-orange-500 text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
//                     Sign Up
//                   </button>
//                 </SignUpButton>
//               </SignedOut>
//               <SignedIn>
//                 <UserButton />
//               </SignedIn>
//             </div>
//           </header>
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }
